### ISSUE TITLE
Double login on first visit

### ISSUE THREAD

**Issue by garthomite** [vhs/nomos#139]
When you first visit the page you'll get something like this

![screenshot 2015-11-19 15 43 39](https://cloud.githubusercontent.com/assets/549549/11287981/b8710e32-8ed4-11e5-8dd9-571a77272512.png)

This is because api methods are being called and return this header:

```
WWW-Authenticate:Basic realm="Nomos"
```

```
curl -D -  http://membership.hackspace.ca/services/web/MetricService1.svc/GetNewMembers
HTTP/1.1 401 Unauthorized
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 19 Nov 2015 23:49:28 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.6.15-1+deb.sury.org~trusty+1
Set-Cookie: PHPSESSID=99brt3pqfo2f0uo973nkb6rsk5; path=/
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
WWW-Authenticate: Basic realm="Nomos"
```

Removing this header will stop chrome from prompting for a login.

**Comment by laftho** [comment]
The main issue here is the angular users.home state is trying to call their resolves at the same time as the resolves for the users state (the abstract parent). ideally we'd make the resolve for the users state that checks the current user would cancel the other resolves... not sure if we can put in a cancel state or something. I added some code that throws an login exception to at least prompt the login screen.

**Comment by laftho** [comment]
although we could make the promises or resolves check if they are logged in before usage, etc, etc.. the cleanest solution I found was to empty out user.home and make it just do a logic check for current user and redirect to a newly created Dashboard page.

/ is still user.home, that'll resolve currentuser which throws error for login. Rather than user.home, which is resolving before it's parent (abstract user) who has the currentuser resolve, user.home doesn't resolve anything, allows the parent to resolve and get the exception. This will then redirect to login without the running any of the dashboard resolves. After login it goes back to / url (user.home) checks current user and redirects to user.dashboard.

https://github.com/vhs/nomos/pull/158

Resolved.
