### ISSUE TITLE
After a donation my membership is being reported as a donation.

### ISSUE THREAD

**Issue by TomKeddie** [vhs/nomos#181]
https://www.paypal.com/ca/vst/id=3BU9263708480050M

https://www.paypal.com/ca/cgi-bin/webscr?cmd=_view-a-trans&id=5MB19642F2218401X

I didn't do this to make things hard for you, I promise.

**Comment by laftho** [comment]
@TomKeddie this is a known situation. We've changed how the subscriptions are handled and there is a transition period for @JarrettR to fix the subscriptions in paypal so they come in with the correct item_number. PayPal is a bit of a steaming pile of garbage so they haven't made it easy to fix our subscriptions. You can cancel your current subscription and re-subscribe to the new button and it will fix it, otherwise @JarrettR should have it resolved sooner than later.

Thanks for the heads up, we'll fix your latest payment in Nomos.

**Comment by TomKeddie** [comment]
Thanks, if he hasn't got to it in 30 days I'll resubscribe.

**Comment by JarrettR** [comment]
It's good to have this open. Informs others that might be confused, and also lights a fire under my ass to fix it :)

**Comment by laftho** [comment]
PR https://github.com/vhs/nomos/pull/201 should effectively address this issue. Although it isn;t exactly a proper fix because it's hardcoded remapping of the legacy i
