### ISSUE TITLE
Dashboard tweaks

### ISSUE THREAD

**Issue by lukecyca** [vhs/nomos#227]
Awesome work! There is some great information here and you've really made it accessible. Really freak'n awesome.

Here are some comments which you can take or leave. Feel free to close this issue if you've considered these and think I'm out-to-lunch.

**Expected revenue** - it wasn't clear to me what this was showing at first. The labels "this month" and "last month" suggest that we are expecting less revenue this month.
I suggest changing the title to "Expected Monthly Revenue" and the labels to "This month to-date" and "Last month actual".

**New members & New keyholders** - These are great stats for everyone to know. It doesn't say in what time period. I suggest renaming to "New members this month" or "December new members" etc.

**Signup times** - these are perfect. Very clear.

**Annual revenue & Change in membership** - these are the most useful graphs! The way the current (partial) month is handled is misleading though.
I suggest leaving off the current month. As-is it is not useful on this graph, since it is not useful to compare the partial month vis-a-vis the trend of monthly actuals.
Alternatively, you could try project the current month in its entirety, either by scaling up based on how much of the month is elapsed (yuck), or doing something more accurate based on knowledge of when recurring payments are coming. Since the point of this is a long-term trend, I think leaving off the current month is an acceptable tradeoff.

**Change in membership** - I suggest removing the "total" line since it is in the previous graph already, and changing the units of this graph from CAD to just the number of members who joined/left.

BTW, CDN isn't the currency code for Canadian Dollar. It's CAD.

I'm done bikeshedding. :)

**Comment by laftho** [comment]
Great feedback! More than welcomed 👍 

Expected revenue - fixed
New members & New keyholders - added period context
Signup times - thank you
Annual revenue & Change in membership - removed current month (because it's partial)
Change in membership - total is actually the total count of members counted by paypal payments we got in the month, doesn't include cash members so it's not absolute but close. The total current members on the top of the page is correct (as in, includes cash members). I've reworded some parts for context.

updated to CAD.

Thanks!
