### ISSUE TITLE
Cash member system

### ISSUE THREAD

**Issue by JarrettR** [vhs/nomos#4]
Adding a new flag to user profiles - "cash member" which handles accounts a little differently.

With this flag set, they will show up on a new page for bulk-adding months onto their membership.

Fields contain name, date paid up to, and a button to mark them as "inactive" and remove them from the page

**Comment by laftho** [comment]
Admins can now set users as cash users and filter the lists by cash users. https://github.com/vhs/nomos/pull/165

We need to still add a way for admins to record cash payments so that our payment records reflect it.

ie.

Admin section "Record cash payment" show a list of cash users, click record payment, enter payment amount and date. Once the Payment object is saved in Nomos it would trigger the payment process automagically and update their account accordingly so this should actually be pretty trivial to implement.

We should record additional information with the cash payment, perhaps the user who is recording it, consider implementing a deposit type system where cash payments are then verified with bank account API.

Cash receipt recorded -> into a pending verification step -> once verified create actual Payment object

**Comment by JarrettR** [comment]
All of the applicable stuff in here has been added to the new system.  Issues #221 and #240 track the still-relevant portions
